import { DEV } from 'esm-env';

let uid = 0;

/**
 * Generate a unique id for a query/command/form function. SvelteKit derives these
 * ids from the `.remote.ts` file path at build time; since local functions are
 * plain runtime factories, a monotonically increasing counter is used instead.
 */
export function next_id(kind: string): string {
	return `${kind}:${++uid}`;
}

/**
 * Serialize a query/command argument into a stable cache-key payload.
 *
 * Mirrors SvelteKit's `stringify_remote_arg` semantics — `undefined` becomes the
 * empty payload and object property order does not affect the key — but uses plain
 * JSON instead of devalue. This means arguments must be JSON-serializable
 * (`Date` works via `toJSON`; `Map`/`Set`/`BigInt` are rejected).
 */
export function stringify_arg(arg: unknown): string {
	if (arg === undefined) return '';

	const json = JSON.stringify(arg, (_key, value) => {
		if (value !== null && typeof value === 'object') {
			if (DEV && (value instanceof Map || value instanceof Set)) {
				throw new Error(
					'Map and Set cannot be used as query/command arguments in svelte-local-query — ' +
						'arguments must be JSON-serializable so they can be used as cache keys. ' +
						'Use an array or plain object instead.'
				);
			}

			if (!Array.isArray(value)) {
				const proto = Object.getPrototypeOf(value);

				if (proto === Object.prototype || proto === null) {
					// sort keys so that property order does not affect the cache key
					const sorted: Record<string, unknown> = {};
					for (const key of Object.keys(value).sort()) {
						sorted[key] = value[key];
					}
					return sorted;
				}
			}
		}

		return value;
	});

	return json === undefined ? '' : json;
}

/** Create the cache key for a `(function id, serialized argument)` pair. */
export function create_key(id: string, payload: string): string {
	return id + '/' + payload;
}

export function split_key(key: string): { id: string; payload: string } {
	// ids generated by `next_id` never contain a slash, but JSON payloads can,
	// so split on the first separator (unlike kit, whose base64 payloads can't)
	const i = key.indexOf('/');

	if (i === -1) {
		throw new Error(`Invalid cache key: ${key}`);
	}

	return {
		id: key.slice(0, i),
		payload: key.slice(i + 1)
	};
}
